### ISSUE TITLE
plot_hit_pattern mini analysis doesn't work with log norm

### ISSUE THREAD

**Issue by reallsx** [XENONnT/straxen#1073]
**Describe the bug**
Mini analysis `plot_hit_pattern` cannot run when specified `log_scale=True`.  This is because PMTs with area 0 gives invalid `vmin` when using log scale. 

This also happens when using `plot_pmts` to plot hit patterns from peaks.

**To Reproduce**
Just try this on any tpc run:
```python
st.plot_hit_pattern(run_id, seconds_range=(0, 0.1), log_scale=True)
```

**Expected behavior**
Hit patterns should be displayed with log norm color map.

**Versions**

```
straxen   1.8.2 /opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.8/site-packages/straxen None
```

**Comment by JoranAngevaare** [comment]
This can easily be sloved with addding a `vmin` argument,
```python
straxen.plot_pmts(np.arange(494), log_scale=True,)  # craches
straxen.plot_pmts(np.arange(494), log_scale=True, vmin=1)  # works fine
```
