### ISSUE TITLE
URLConfig in peak_s1_position_cnn.py

### ISSUE THREAD

**Issue by matteoguida** [XENONnT/straxen#1157]
`straxen.URLConfig` is not working properly in `peak_s1_position_cnn.py` [https://github.com/XENONnT/straxen/blob/9e8126e67554575c66d89322e33c8354df88fc3d/straxen/plugins/peaks/peak_s1_position_cnn.py#L19](https://github.com/XENONnT/straxen/blob/9e8126e67554575c66d89322e33c8354df88fc3d/straxen/plugins/peaks/peak_s1_position_cnn.py#L19) can be seen running `https://github.com/XENONnT/analysiscode/blob/master/s1_pos_rec/test_s1_cnn_peak_level.py`. Instead uncommenting the line [https://github.com/XENONnT/straxen/blob/9e8126e67554575c66d89322e33c8354df88fc3d/straxen/plugins/peaks/peak_s1_position_cnn.py#L18](https://github.com/XENONnT/straxen/blob/9e8126e67554575c66d89322e33c8354df88fc3d/straxen/plugins/peaks/peak_s1_position_cnn.py#L18) commenting L19-L31 it should run.

**Comment by dachengx** [comment]
Would you please demo the detailed error message? @matteoguida It is helpful to probe whether the error originates from different environments and also can help other people to get involved. : )

**Comment by jmosbacher** [comment]
This was due to a bug in frame. 
It is fixed in rframe version 0.2.8, xedocs version 0.2.16 uses the fixed version of rframe.
