### ISSUE TITLE
Separate event_area_per_channel and event_waveform

### ISSUE THREAD

**Issue by shenyangshi** [XENONnT/straxen#1187]
The current EventAreaPerChannel plugin contains too much redundancies, including S1/S2 main/alt patterns as well as S1/S2 main/alt waveforms, this doubles the size of this plugin, making dali/midway suffer so it's not stored anymore confirmed by @FaroutYLq.

@minzhong98 @jpienaar13, do you think it's possible to separate this to get the data available for the S1/S2 pattern cut?
The task should be:
1. Separate two plugins like event_area_per_channel and event_waveform.
2. Evaluate the typical file size for a run for different run types, such as Kr83m/Rn220/science runs.

![image](https://github.com/XENONnT/straxen/assets/70266165/0163ecc0-ed65-4cdf-afeb-847526c6e62f)

**Comment by dachengx** [comment]
MISSION ACCOMPLISHED by https://github.com/XENONnT/straxen/pull/1191
