### ISSUE TITLE
Want non-overlapping assertion before `abs_time_to_prev_next_interval`

### ISSUE THREAD

**Issue by FaroutYLq** [XENONnT/straxen#1213]
Since we removed the check of overlapping in `abs_time_to_prev_next_interval`, as what [this PR](https://github.com/AxFoundation/strax/pull/738#event-9746554951) did, we want to put it back in `straxen`. It would be really mess-up if events are overlapping...

Seems currently [this](https://github.com/XENONnT/straxen/blob/d0b935c98fc2f940664da100c58de07a1e2bf0bf/straxen/plugins/events/veto_proximity.py#L103) is the only place in `straxen` using such function

**Comment by dachengx** [comment]
I believe this is fixed at https://github.com/XENONnT/straxen/pull/1214.
