### ISSUE TITLE
Lone_hits sticking out of a chunk

### ISSUE THREAD

**Issue by JelleAalbers** [XENONnT/straxen#124]
When processing runs with the latest strax + straxen, I get these errors in 4/~450 runs (7769, 7770, 7775, 7795):

```
ValueError: Attempt to create chunk [007769.lone_hits: 1589849417sec 999999000 ns - 1589849423sec 499999000 ns, 912904 items, 6.6 MB/s] whose data ends late at 1589849423499999280
```

```
ValueError: Attempt to create chunk [007775.lone_hits: 1589870842sec 999999000 ns - 1589870848sec 499999000 ns, 922094 items, 6.7 MB/s] whose data ends late at 1589870848499999130
```

They appear at some seemingly random time in the run, and given how rare they are, this could be an edge case in one of the algorithms. It would be surprising though; in strax, hits shouldn't be able to extend beyond the record they are part of. (Peak(let)s could, but for peaks PulseProcessing explicitly clips them to chunk boundaries.)

Since three of the failing runs are close together, maybe there is simply something wrong with the records for these runs, and the error will disappear in future reprocessings?

**Comment by jorana** [comment]
This is fixed in:
https://github.com/XENONnT/straxen/pull/146

Also the check is extended a bit such that the underlying error in raw_records would have popped up.
https://github.com/AxFoundation/strax/pull/281
