### ISSUE TITLE
Avoid C / C++ compilations in test build

### ISSUE THREAD

**Issue by JelleAalbers** [XENONnT/straxen#131]
Currently, Travis builds spend a long time compiling some C++ modules, according to a long stream of warnings like
```
cc1plus: warning: command line option ‘-std=gnu99’ is valid for C/ObjC but not for C++
```

It's not super clear what the main culprit is, maybe grpcio? Probably we can install some things via conda to avoid this.

**Comment by jorana** [comment]
Cannot confirm, it looks like this might be out of date feel free to reopen if needed
