### ISSUE TITLE
y-axis of time_v_channel graph in waveform_display not correct

### ISSUE THREAD

**Issue by cheryonthetop** [XENONnT/straxen#135]
#128 loads data and shows the graph. But the waveform_display graph has a little problem: Notice the PMT number goes from 0 to 1, when it should go from 0 to number of channels.
![bokeh_plot_3](https://user-images.githubusercontent.com/50539795/85252576-af711180-b48e-11ea-9175-0c828e066b52.png)
The code to reproduce the plot is:
```
import straxen    
st = straxen.contexts.xenon1t_dali(build_lowlevel=True)
run_id = '170204_1710'
df = st.get_array(run_id, "event_info")
event = df[4]
st.waveform_display(run_id, time_within=event)

**Comment by jorana** [comment]
@cheryonthetop looks like you fixed it right? Maybe we can close the issue (feel free to re-open).
