### ISSUE TITLE
dt field DAQreader

### ISSUE THREAD

**Issue by WenzDaniel** [XENONnT/straxen#136]
The proposed one DAQ one DAQreader solution of the linked-mode requires a change of the DAQreader. Currently the dt field is specified as an option which wont work any longer.

**Comment by jorana** [comment]
I think we can add it as a field to the channel_map:
https://github.com/XENONnT/straxen/blob/master/straxen/plugins/daqreader.py#L58

As you have pointed out before, the tricky bit comes in the breaking bit (https://github.com/XENONnT/straxen/blob/master/straxen/plugins/daqreader.py#L180). 

Perhaps we can rechunck the ' raw_records_nv' if we cannot find save breaks when combined with the TPC raw_records (https://github.com/AxFoundation/strax/pull/272)

**Comment by WenzDaniel** [comment]
> I think we can add it as a field to the channel_map:

Sounds good. Though I did not understand why we cannot read the field from data itself and pass it as an argument or whatever. I have to look into the DAQreader once more. I had not any time yet. 

>As you have pointed out before, the tricky bit comes in the breaking bit.

Hmm not sure. From what I can recall is the gap requirement for TPC larger as for the nVETO. The nVETO would require something like 300 ns - 600 ns while I think it is currently set to 1 µs. 
For the nVETO  or better say for the recorder plugin it will become problematic if we cannot find any gap an therefore fall back to the "take largest possible gap"-option.

Here I would propose to be simply practical. The nveto-recorder plugin does not have to be super exact. It shall just reject the huge amount of dark rate by applying this simple n-fold coincidence between records. Hence, I could add to the nveto_recorder that we store the last n-1 records per chunk independent of the coincidence outcome. In this way we would not suffer any data loss if we split chunks in gaps smaller than e.g. 300 ns.

**Comment by WenzDaniel** [comment]
As result of yesterdays straxferno: 

We should also check whether we have to change line 68 in strax.chunk.py since we cannot guarantee that the end time of e.g. the last (by index) raw_record in a chunk yields the highest endtime.

**Comment by darrylmasson** [comment]
What's the status on this? At some point in the future we'll want to test the fully-integrated DAQ, and a compatible DAQReader is necessary.

**Comment by jorana** [comment]
@darrylmasson, would you be able to make some live-data (e.g. using your rough simulator) in the right format in such a way that I can test some ideas. Atm I have been postponing it because I am not 100% sure on the format we should convert.

**Comment by darrylmasson** [comment]
Do we specifically want data with varying `dt` fields? I can tweak the simulator to use a random number for that if we want

**Comment by jorana** [comment]
If you can replicate some data with e.g. channel 0 at 10 ns and channel 2000 as 2 ns that would be all I need. It preferably is in the same format as you would expect the tpc and nv -data to be written out by the readers.

**Comment by jorana** [comment]
Fixed in #270
