### ISSUE TITLE
Remove `resource_cache` on dali

### ISSUE THREAD

**Issue by dachengx** [XENONnT/straxen#1362]
At https://github.com/XENONnT/straxen/blob/e7d95878b091ebe0a6d80732b256ba677c7a6ba1/straxen/common.py#L264 and https://github.com/XENONnT/straxen/blob/e7d95878b091ebe0a6d80732b256ba677c7a6ba1/straxen/storage/mongo_storage.py#L264 we stored `resource_cache` files on `/dali`. But sometimes `/dali` is not accessible because `/dali` and `/project(2)` are decoupled. I am wondering if we can remove the `resource_cache` on dali.

**Comment by yuema137** [comment]
I think letting users store the resource_cache under their local folders doesn't harm, as the size of those caches is not terrible. So, should we just remove the dali path from the list?
