### ISSUE TITLE
(Improvment) Add baseline_value and baseline_rms to pulse_counts.

### ISSUE THREAD

**Issue by WenzDaniel** [XENONnT/straxen#139]
pulse_counts are very useful to monitor the PMT count rate in our TPC. To be able to cross check if a higher PMT rate is caused by either an increased signal rate or change in noise, I would like to propose to add two additional fields to pulse_counts. The first field stores the average baseline value per PMT and in the second field we store the average baseline rms per PMT. Just as a comparison: 

Loading pulse_counts of a single 1h nitrogen run takes 1.10 s while loading the baseline and baseline_rms values stored in records of the very same run takes about 10 min.

**Comment by WenzDaniel** [comment]
https://github.com/XENONnT/straxen/pull/140

**Comment by jorana** [comment]
As this is merged to master I think we can safely close this issue
