### ISSUE TITLE
Trim CNN and GCN from the dependency tree for SR2 

### ISSUE THREAD

**Issue by yuema137** [XENONnT/straxen#1444]
For SR2, we will only use CNF and MLP for the position reconstruction, considering their better performance. 
CNN and GCN should, therefore, be trimmed from the dependency tree to avoid unnecessary massive processing. However, the plugins should be kept for potential cross-checking.

**Comment by dachengx** [comment]
Related [slack thread](https://xenonnt.slack.com/archives/C016UJZ090B/p1728575173324429)

**Comment by yuema137** [comment]
Fixing PR: #1449

**Comment by juehang** [comment]
Looks good, I assume the tests failing is due to #1452 ? Also, is the plan to push this for now and add another PR after reprocessing and after the FDC map has been constructed?
