### ISSUE TITLE
`defualt_run_comments` -> `default_run_comments`

### ISSUE THREAD

**Issue by dachengx** [XENONnT/straxen#1485]
https://github.com/XENONnT/straxen/blob/e222b25e3f3b284c16d78e8607ab2de410af8b25/straxen/plugins/led_cal/led_calibration.py#L59

**Comment by GiovanniVolta** [comment]
What is this? Mor information?

**Comment by dachengx** [comment]
A typo. `defualt_run_comments` should be `default_run_comments`
