### ISSUE TITLE
Error in time range handling waveform plot

### ISSUE THREAD

**Issue by jorana** [XENONnT/straxen#149]
**Problem**
Something goes wrong when plotting small time ranges in st.plot_peaks. 

**Symptons**
See below:
![afbeelding](https://user-images.githubusercontent.com/22295914/87221874-bd200580-c36f-11ea-9e79-221b83030424.png)

(start time is 1594353486000000000)

**Traceback**
https://gist.github.com/jorana/c0b8e36486250ca38e25b96d59237624

**Software**
![afbeelding](https://user-images.githubusercontent.com/22295914/87221918-f35d8500-c36f-11ea-9820-a93d43934d12.png)
running on dali

**Comment by jorana** [comment]
@cheryonthetop would you think you could have a look?

**Comment by JelleAalbers** [comment]
Could be related to https://github.com/AxFoundation/strax/issues/247?

**Comment by jorana** [comment]
It can be related. Unfortunately the mentioned work around does not work for the runs where I ran into this problem as the datarate is so high that there are no evident slightly wider time ranges that allow me to load the data.

**Comment by jorana** [comment]
Should be fixed in AxFoundation/strax#345 rather than #261
