### ISSUE TITLE
Convert 'daq times' to epoch times

### ISSUE THREAD

**Issue by coderdj** [XENONnT/straxen#17]
The DAQ provides timestamps in ns since run start with resolution of the ADC sample size. This needs to be converted to 'ns since unix epoch'. This is hard to do in the DAQ but maybe it can be done in the DAQReader plugin at the stage where all the sub-files from each readout thread are combined.

**Comment by JelleAalbers** [comment]
I guess this would involve:
  * Add an option such as run_start_time to the DAQReader;
  * Add the epoch time in ns of the run start to the DAQ times in the records here https://github.com/XENONnT/straxen/blob/master/straxen/plugins/daqreader.py#L112;
  * Modify bootstrax to pass the run doc's start time as an argument to run_strax here https://github.com/XENONnT/straxen/blob/master/bin/bootstrax#L534 and eventually to strax itself here https://github.com/XENONnT/straxen/blob/master/bin/bootstrax#L469;
  * Testing this by processing a run

**Comment by jorana** [comment]
This issue is addressed by this commit (https://github.com/XENONnT/straxen/commit/569c80334b8373ed419be83d54c78b6d22e18ee0) as part of PR https://github.com/XENONnT/straxen/pull/29.
