### ISSUE TITLE
Processing muon veto data

### ISSUE THREAD

**Issue by jorana** [XENONnT/straxen#173]
At the moment we stop at raw_records_mv. If we want to reproduce the 1T-like muon-veto the bare minimum is that we build some muon_veto regions where timestamps in between are vetoed. This should be possible with the existing peak-finding.

**Comment by WenzDaniel** [comment]
I discussed this already with Andrea. The idea would be to use the nveto plugins (except for the recorder plugin). We would implement them in the same way as we did for the HE channels,

**Comment by jorana** [comment]
Yes I opened this issue partially to make note of #175. If we do it the same way we are doing for the He channels we have to be practical about what we want to store and what not. Otherwise we might end up with so many plugins that we get ~50 different datatypes per run which will become quite a computational nightmare to track over time.

**Comment by jorana** [comment]
See PRs:
https://github.com/AxFoundation/strax/pull/355
https://github.com/XENONnT/straxen/pull/287/files
