### ISSUE TITLE
Make sure to update pulse_length in clean_up_empty_records

### ISSUE THREAD

**Issue by jorana** [XENONnT/straxen#179]
We need to make sure to update pulse_length in
https://github.com/XENONnT/straxen/blob/master/straxen/plugins/nveto_pulse_processing.py#L69 as it might lead to funny behavior down the chain.

**Comment by WenzDaniel** [comment]
Once the issue is fixed we should also apply this function to PulseProcessing

**Comment by jorana** [comment]
I agree, let's schedule this to be done while also updating the hit-finder thresholds

**Comment by WenzDaniel** [comment]
Solved in #210
