### ISSUE TITLE
Plugins omit description

### ISSUE THREAD

**Issue by jorana** [XENONnT/straxen#190]
The majority of the plugins omit a description. For documentation we should add a description to all plugins. 

For a plugin description see e.g. the DAQreader:
https://github.com/XENONnT/straxen/blob/master/straxen/plugins/daqreader.py#L62

Perhaps @WenzDaniel can help with the NVeto plugins

**Comment by WenzDaniel** [comment]
Sure, I can also help with the low level plugins of the TPC. Maybe we should discuss first which information exactly to include. I think also the DAQreader example is not ideal.

**Comment by jorana** [comment]
Okay, fair enough perhaps the records one is better:
https://straxen.readthedocs.io/en/latest/reference/datastructure.html#id61

If possible I think it should be concise (if you want to know all the details in the code you can better read the code) but explaining the most important steps taken in that plugin such that it's clear what we did between output and input. Would you agree?

**Comment by jorana** [comment]
There was a whole series of PRs to fix this:
- https://github.com/XENONnT/straxen/pull/185
- https://github.com/XENONnT/straxen/pull/187
- https://github.com/XENONnT/straxen/pull/189
- https://github.com/XENONnT/straxen/pull/192
- https://github.com/XENONnT/straxen/pull/198
- https://github.com/XENONnT/straxen/pull/199
- https://github.com/XENONnT/straxen/pull/200
