### ISSUE TITLE
Interface to job submission system for general analysis

### ISSUE THREAD

**Issue by briedel** [XENONnT/straxen#2]

**Comment by tunnell** [comment]
There's no description here so this isn't clear.  Also, job submission is probably out of scope.

**Comment by JelleAalbers** [comment]
I think this relates to a comment I made on the computing overview: 

It would be great if we could have an interface between strax(en) and a job submission system, so analysts can such high-level processing jobs themselves (maybe not for the full science run), for example to explore alternative settings or create their own 'minitrees'. Ideally you could do this right from the notebook.

Currently many analysts have some version of a 'minitree maker batch submission script' that is making the rounds (and others just use the login node when nobody is looking).

This somewhat relates to the idea Chris was exploring with 'requests' in https://xenon-shox.appspot.com/request

@tunnell Indeed, this doesn't have to be in straxen, though it could be.

**Comment by tunnell** [comment]
We discussed this during Stockholm workshop, right?  With delayed DataFrame?  That's the intention with request (though right now doesn't let you override settings, but made easy to add) and snax at least.  

The idea of having a queue that people can add work to sort of addresses this, right?

**Comment by JelleAalbers** [comment]
@sophiaandaloro is working on a job submission system currently, her code is here https://github.com/XENONnT/analysiscode/tree/he_veto/he_veto.

**Comment by jorana** [comment]
Perhaps it's fine to just leave this to utilix, as such, let's close this:
https://github.com/XENONnT/utilix/blob/master/utilix/batchq.py
