### ISSUE TITLE
Support nfold=1 for nVETORecorder Plugin

### ISSUE THREAD

**Issue by WenzDaniel** [XENONnT/straxen#203]
For commissioning it might be nice to save all raw_records_nv.

**Comment by jorana** [comment]
Would this be something for the main context/straxen? I imagine that we just ship some of the ``raw_records_nv`` to dali where they aren't removed by ajax: https://github.com/XENONnT/straxen/blob/master/bin/ajax#L258

**Comment by WenzDaniel** [comment]
This would be just a small addition, that a user can process all raw_records_nv up to hitlets_nv if needed (without having an extra plugin which would change lineage, make things complicated, causes issues and problems etc. :D).

**Comment by jorana** [comment]
> This would be just a small addition, that a user can process all raw_records_nv up to hitlets_nv if needed (without having an extra plugin which would change lineage, make things complicated, causes issues and problems etc. :D).

Of course, if we save some of these raw_records_nv you can make hitlets et cetera with whatever setting you like. I thought you wanted to something to straxen for this but it looks like this issue (203) is more like a mental note.

**Comment by WenzDaniel** [comment]
> I  thought you wanted to add something to straxen

I have to modify the reader such that it allows to pass the data without building any coincidence. Currently this is not featured.

**Comment by jorana** [comment]
> 
> 
> > I  thought you wanted to add something to straxen
> 
> I have to modify the reader such that it allows to pass the data without building any coincidence. Currently this is not featured.

The reader or the recorder? I thought you just use this one: https://github.com/XENONnT/straxen/blob/master/straxen/plugins/nveto_recorder.py#L13 otherwise you probably want to use the same option name to prevent inconsistancies

**Comment by WenzDaniel** [comment]
My mistake sorry, I should have been a bit more explicit. Yes I mean the recorder and the option you are referring to. But currently if you specify anything below 2  you will just get an error message.

**Comment by WenzDaniel** [comment]
Solved in https://github.com/XENONnT/straxen/pull/316
