### ISSUE TITLE
Data management on eventbuilders

### ISSUE THREAD

**Issue by jorana** [XENONnT/straxen#205]
Yesterday runs 9236, 9237, 9238 were irrecoverably lost from the event builders. The big question is how it can be that we at some point seem to have lost the data stored on `/data/xenonnt_processed` or have somehow passed [line 586](https://github.com/XENONnT/straxen/blob/fd7c2c9301408056c05b8e17ea44ed4a548fc712/bin/ajax#L586) in `Ajax`.

The reason turned out to be a faulty logic in [this line](https://github.com/XENONnT/straxen/blob/fd7c2c9301408056c05b8e17ea44ed4a548fc712/bin/ajax#L518) that said that that are less than two hours old should be deleted. 

**RECONSTRUCTION**
These are the events that happened (focusing on runs 9236).

**"2020-08-31T18:05:47.776Z" - Processing finished**
`Bootstrax` successfully processed the run and then deleted the [live_data at this time ](https://github.com/XENONnT/straxen/blob/3b9a7ae1694f6b4dc22163e02c8883c5eab37087/bin/bootstrax#L1290) which is only done after we have successfully stored all the data (there is a [check in](https://github.com/XENONnT/straxen/blob/3b9a7ae1694f6b4dc22163e02c8883c5eab37087/bin/bootstrax#L901) ```set_status_finished``` that makes sure the data has been written to disk). Furthermore, one can see from the deleted entries that we have saved .
![afbeelding](https://user-images.githubusercontent.com/22295914/91857607-65639380-ec68-11ea-817b-7ea75b7822a0.png)

**"2020-08-31T19:.." - `Ajax` deletes the 'unregistered' data**
[The bug was here](https://github.com/XENONnT/straxen/blob/fd7c2c9301408056c05b8e17ea44ed4a548fc712/bin/ajax#L518)
```
7208899 MainThread root clean_unregistered::    found 398 runs stored on/data/xenonnt_processed/. Checking that each is in the runs-database
7209768 MainThread root remove_if_unregistered::        run 9236 is NOT registered in the runDB
7209768 MainThread root No data for 009236 found! Double checking /data/xenonnt_processed/!
7209769 MainThread root Cleaning /data/xenonnt_processed/009236-raw_records_nv-rfzvpzj4mf
7209770 MainThread root Cleaning /data/xenonnt_processed/009236-raw_records_aqmon-rfzvpzj4mf
```

**"2020-08-31T20:18:53.934Z" - `Ajax` removes entries from runs-database**
In the [clean_database routine](https://github.com/XENONnT/straxen/blob/fd7c2c9301408056c05b8e17ea44ed4a548fc712/bin/ajax#L559), `ajax` notices that this run is stored for >2 h and that processing has finished. For this we check if the data is actually stored on this host on [line 586](https://github.com/XENONnT/straxen/blob/fd7c2c9301408056c05b8e17ea44ed4a548fc712/bin/ajax#L586). The corresponding output from `ajax` is added below:
```
10812030 MainThread root Loop finished, take a 3600 s nap
14412139 MainThread root clean_unregistered::   found 396 runs stored on/data/xenonnt_processed/. Checking that each is in the runs-database
14412978 MainThread root clean_abandoned::      No more matches in rundoc
14413442 MainThread root clean_database::       delete entry of data from 9236 at /data/xenonnt_processed/009236-raw_records_aqmon-rfzvpzj4mf as it does not exist
14413442 MainThread root deleting /data/xenonnt_processed/009236-raw_records_aqmon-rfzvpzj4mf finished
14413442 MainThread root changing data field in rundoc
14413442 MainThread root update with {'host': 'eb5.xenon.local', 'type': 'raw_records_aqmon', 'file_count': 36, 'at': datetime.datetime(2020, 8, 31, 20, 18, 53, 934849, tzinfo=<UTC>), 'by': 'eb5.xenon.local.ajax'}
...
```
**"2020-08-31T20:19:05" - `Bootstrax` notices that all processed data is now removed and fails the run**
Please note that this further substantiates that the processing did occur as needed.

![afbeelding](https://user-images.githubusercontent.com/22295914/91857875-cee3a200-ec68-11ea-8e1f-035de7b8aece.png)

**Comment by darrylmasson** [comment]
`remove_if_unregistered` is something we should think about removing. It was useful earlier in commissioning, but as we continue developing the full package and creep ever close to actual science data, "legitimate" cases of unregistered data should continue to decrease (I think they have largely vanished for the most part), and there will be quite a stink if we accidentally delete science data through an unforeseen loophole like this.

**Comment by jorana** [comment]
> `remove_if_unregistered` is something we should think about removing. It was useful earlier in commissioning, but as we continue developing the full package and creep ever close to actual science data, "legitimate" cases of unregistered data should continue to decrease (I think they have largely vanished for the most part), and there will be quite a stink if we accidentally delete science data through an unforeseen loophole like this.

I do see your point. It also went against my initial idea of having every single deletion going through the function ``delete_data`` (with it's associated checks). On the other hand, it's nice if the runs-database and the eventbuilders are a true representation of one another without funny/un-tracked files lying around. Perhaps we can find some middle ground by changing the function to **move** rather than remove the data to a location. E.g. we crate a folder on each event-builder ```/data/unregistered```. I fully agree, this folder should stay empty, any files ending up there are a sign something is off which need special attention.
