### ISSUE TITLE
Throw a warning if fried rice is down insteat of crashing everything.

### ISSUE THREAD

**Issue by WenzDaniel** [XENONnT/straxen#211]
In our current implementation of the rundb.py straxen raises an error when fried rice is down:

```
~/mymodules/straxen/straxen/rundb.py in _find(self, key, write, allow_incomplete, fuzzy_for, fuzzy_for_options)
    153                         'protocol': 'rucio'}}}
    154             doc = self.collection.find_one({**run_query, **dq},
--> 155                                            projection=dq)
    156             if doc is not None:
    157                 datum = doc['data'][0]

# (some long mongo trace back)

ServerSelectionTimeoutError: fried.rice.edu:27017: timed out
```

This issue was introduced with https://github.com/XENONnT/straxen/pull/164/files .

In most cases analyzers will work with locally stored data and hence do not need to access anything via the rundb storage system. Hence I propose rather to throw a warning and to drop the rundb storage system from the registered storage rather than raising an error and stopping any ongoing analysis.

**Comment by WenzDaniel** [comment]
Evans PR makes this issue obsolete

**Comment by jorana** [comment]
@WenzDaniel #164 is not related to this issue. Rather https://github.com/XENONnT/straxen/pull/114 is the cull-pit.

**Comment by jorana** [comment]
An alternative solution is proposed in #213 using the other two mirrors as backup in order not to prevent analyzers to work outside of dali (see cited PR)
