### ISSUE TITLE
Rucio does not check options

### ISSUE THREAD

**Issue by petergaemers** [XENONnT/straxen#227]
Issue:

- Loading data from the rucio catalogue does not check if the versions and options match the strax configuration.

More specifically, the function ```st.is_stored(run_id,data_type)``` will always return true if there is any data of that data_type and run in the rucio database. The lineage is not checked.

Example:
```
import straxen
st = straxen.contexts.xenonnt_online()
st.set_config(dict(s1_max_rise_time=50000,
                  peak_split_filter_wing_width=1000000))
st.is_stored('009149','peak_basics')
st.get_array('009149','peak_basics')
```
 
The data belonging to this configuration does not exist. However since is_stored will return true anyway, get_array will retrieve the data from rucio despite it having different settings

**Comment by jorana** [comment]
Fixed in  #242
