### ISSUE TITLE
Generalized class of using tensorflow models

### ISSUE THREAD

**Issue by zhut19** [XENONnT/straxen#234]
Is there a plan to have a generalized rapper for tf models, that takes a similar role to https://github.com/XENONnT/straxen/blob/e940bf3bf915ddf89f1754fbc0aa99af11385e94/straxen/itp_map.py#L58

I guess it ties to the issue raised by @tunnell, one advantage of such a rapper is for example reduce pos.rec. plugin to just one, and using just a config string to change between algorithms.
https://github.com/XENONnT/straxen/blob/429a7be84263814a6880c47e994a29d87718bae5/straxen/plugins/peak_processing.py#L159

Although my feeling with the aforementioned  itp_map in 1T was mixed, on one hand, the processing plugins and hax are cleaner because of it, while itp_map itself is very complicated and hard to understand.

**Comment by jorana** [comment]
Fixed in #323 right? Feel free to reopen if not.
