### ISSUE TITLE
Including required variables information

### ISSUE THREAD

**Issue by zhut19** [XENONnT/straxen#235]
Really, this is an idea for lax. It is not always easy for the analyzer to determine exactly what variables are needed in the cuts,  but it is a simple task for the developers to document it. It should work like what's been done with `requires` and `provides`, but this can be much simpler.

For this, what we need to do is adding a list in class properties. And have an auto-generation function that can grab and concatenate this list from upstream plugins.

**Comment by jorana** [comment]
Although not exactly what you describe, something like ``st.search_field('cs1')`` can be most helpful.

**Comment by JoranAngevaare** [comment]
Fixed in https://github.com/AxFoundation/strax/pull/638
