### ISSUE TITLE
WFSim for Straxen

### ISSUE THREAD

**Issue by nikita-0209** [XENONnT/straxen#274]
Earlier, I didn't use to run into an issue while installing `wfsim`. But I guess recent changes have been made and the installation of `wfsim` fails. Now, I am able to install `WFSim` (case-sensitive) successfully but then I run into an issue while executing the following command.
```
st = strax.Context(
        storage=strax.DataDirectory('./strax_data'),
        register=wfsim.RawRecordsFromFax1T,
        config=dict(detector='XENON1T',
                    fax_config='https://raw.githubusercontent.com/XENONnT/'
                               'strax_auxiliary_files/master/fax_files/fax_config_1t.json',
                    **straxen.contexts.x1t_common_config,),
        **straxen.contexts.common_opts)
```

How can I make this work?

**Comment by petergaemers** [comment]
Whats the error?

**Comment by nikita-0209** [comment]
Error:
`NameError: name 'wfsim' is not defined`

**Comment by petergaemers** [comment]
What does `import wfsim` do?

**Comment by nikita-0209** [comment]
Importing leads to this error: `ModuleNotFoundError: No module named 'wfsim'`

When I try installing wfsim, 
```
ERROR: Could not find a version that satisfies the requirement wfsim (from versions: none)
ERROR: No matching distribution found for wfsim
```

**Comment by petergaemers** [comment]
How do you install wfsim?

**Comment by nikita-0209** [comment]
I tried both: 
1. `pip install wfsim==0.0.6`
2. `pip install wfsim`
Both lead to the same error.

**Comment by petergaemers** [comment]
wfsim is not on pypi. You need to download it from github and do `pip install` in the wfsim folder

**Comment by nikita-0209** [comment]
Like this?:

```
git clone https://github.com/XENONnT/WFSim
pip install -e ./WFSim
```

**Comment by jorana** [comment]
yes that should work.

**Comment by nikita-0209** [comment]
It doesn't. If I run these statements:
```
git clone https://github.com/XENONnT/WFSim
pip install -e ./WFSim
```
And then, try this:
```
st = strax.Context(
        storage=strax.DataDirectory('./strax_data'),
        register=wfsim.RawRecordsFromFax1T,
        config=dict(detector='XENON1T',
                    fax_config='https://raw.githubusercontent.com/XENONnT/'
                               'strax_auxiliary_files/master/fax_files/fax_config_1t.json',
                    **straxen.contexts.x1t_common_config,),
        **straxen.contexts.common_opts)
```
I end up with the error:
`NameError: name 'wfsim' is not defined`

And also, I am suddenly facing issues in importing strax now (was working fine till yesterday). This is how I installed it:
```
git clone https://github.com/XENONnT/straxen
pip install -e ./straxen
import strax
```
And the error is: 
`ModuleNotFoundError: No module named 'strax'`
