### ISSUE TITLE
Travis does not test databases

### ISSUE THREAD

**Issue by jorana** [XENONnT/straxen#277]
As straxen is getting more heavily relying on database access through e.g. the online monitor (#216) and CMT (#220, #251) we should start exploring the opportunity to also let Travis have access to the runsdatabase or at least have access to one run or so that we store as a/multiple CSV file(s)?

Perhaps @tunnell has experience setting this up?

**Comment by tunnell** [comment]
TravisCI has a buildin mongo you can spin up.  I wouldn't use our production server.  You can maybe do a mongo dump then load that on the CI.  It would take some time to setup well is all since we'd also have to make the tests.

**Comment by jorana** [comment]
Finally solved in  #360 😄
