### ISSUE TITLE
Issue Importing strax

### ISSUE THREAD

**Issue by nikita-0209** [XENONnT/straxen#278]
I am suddenly facing issues in importing strax now (was working fine till yesterday). This is how I installed it:
```
git clone https://github.com/XENONnT/straxen
pip install -e ./straxen
import strax
```
And the error is:
`ModuleNotFoundError: No module named 'strax'`

**Comment by jorana** [comment]
Hi Nikita,
Perhaps you want to checkout a tutorial on making your own conda and installing it there?

A good place to start is the following:
```bash
# <<First install conda>>
conda create -n strax python=3.7 # create a conda environment
which python
cd ~/software # or wherever you want to store software
pip install straxen # this should work
git clone https://github.com/XENONnT/WFSim #WFsim is not pip installable
pip install -e WFSim # install
git clone https://github.com/XENONnT/utilix # same here
pip install -e utilix# install
python -c "import straxen; print('Yes, straxen works!')" # test and hopefully success
```

Perhaps it's good to reach out through slack, the github issues are more for code-specific bugs and this seems to be related to your personal installation. 

I just reinstalled straxen to double check, this should work.

**Comment by nikita-0209** [comment]
Hi, I am actually using Google Colab to simulate events. It doesn't have provisions for creating conda environments. I'm sorry but could something else work out?
Yes, I am an undergrad in the nT experiment. I don't have access to the Slack community or the analysis guide (the site asks for credentials) yet. That's why I had to put up an issue.
