### ISSUE TITLE
Autogenerated docs failing for multi-output plugin config options

### ISSUE THREAD

**Issue by JelleAalbers** [XENONnT/straxen#31]
For multi-output plugins, currently only the configuration options of their parent plugins are displayed in the straxen docs. This should be an issue with [build_datastructure_doc.py](https://github.com/XENONnT/straxen/blob/master/docs/source/build_datastructure_doc.py).

**Comment by jorana** [comment]
Fixed in #434

**Comment by jorana** [comment]
That was some extremely long outstanding issue 👴
