### ISSUE TITLE
Documentation Scada and CMT

### ISSUE THREAD

**Issue by jorana** [XENONnT/straxen#315]
Straxen would benefit from more elaborate documentation. Lately some fantastic features were added.

It would be good if we can provide more elaborate documentation of do's and don't for:
1. the OnlineMonitor (I, @jorana can work on that)
2. the ScadaInterface (perhaps @WenzDaniel )
3. CMT (perhas @ahiguera-mx)

Some of these things might be better suitable for this than others as it has to be written in such a way so as not to expose any xenon-secrets. Nevertheless, explaining structures can be very helpfull for other people to be pointed to.

The threshold for writing documentation should be as low as possible. Here is an example of documentation I just on the gridfs interface: https://github.com/XENONnT/straxen/pull/311/commits/889572f7a05a254e14d33f12e113237d9849ed3f

**Comment by WenzDaniel** [comment]
I think we should still add SCADA and CMT is not it? At least it is still on my agenda.

**Comment by jorana** [comment]
yes, this was one of the automatic closing actions of github which was unintended

**Comment by ahiguera-mx** [comment]
I can work on the CMT documentation

**Comment by jorana** [comment]
Fixed, thanks guys!
