### ISSUE TITLE
Seperate top & bottom array waveforms

### ISSUE THREAD

**Issue by petergaemers** [XENONnT/straxen#329]
Due to the size of nT there is a (strongly suspected) difference in the distribution of photon arrival times in the top array compared to the bottom array. This has a large effect on waveform analysis (S1,SE,S2 shapes), and probably many other things I'm not involved in secretly also dependent on this thing like classification and position reconstruction.

I'm currently hacking something together to give it to me, but since it'll be (relatively) computationally expensive and takes up much disk space it would be nice to have it included in the normal data flow as part of peak(let)s. Then other people can benefit from this as well

The actual implementation is not super straightforward. It will require some changes to sum_waveform and other functions in strax to do it nicely

**Comment by terliuk** [comment]
I think it makes sense to have at least timing parameters for both array. I think they are only:

| width | ('<f4', (11,)) | Peak widths in range of central area fraction [ns]  | 
| area_decile_from_midpoint | ('<f4', (11,)) | Peak widths: time between nth and 5th area decile [ns]  |

Another thought we discuss privately. Do I understand correctly that current waveform is top+bottom, so technically we need only one additional waveform (for one array) for full information?

**Comment by petergaemers** [comment]
With storing just 1 of the arrays you could get the other by subtracting it from the full waveform

**Comment by terliuk** [comment]
And how much extra storage will it be for nT data? Would it be acceptable?

**Comment by terliuk** [comment]
I think we need to revitalize our efforts here, as top and bottom waveforms can be really important for S1, SE, optical properties etc matching. @skazama , @petergaemers , @jorana  what do you think?
