### ISSUE TITLE
Raw_Records of demo context have the wrong dtype

### ISSUE THREAD

**Issue by WenzDaniel** [XENONnT/straxen#339]
I just noticed today during some test, that the raw_records of the demo context are still in the old data_type configuration. We may want to change this.

**Comment by jorana** [comment]
Thanks, that indeed sound like something worth fixing. I wonder, perhaps we can even use some simulated nT data to do the tests. Would require some hacking of the lineage but that's not impossible.

**Comment by JoranAngevaare** [comment]
Fixed in #709 #703 #830 https://github.com/XENONnT/strax_auxiliary_files/pull/26
