### ISSUE TITLE
Missing documentation aqusisition monitor

### ISSUE THREAD

**Issue by WenzDaniel** [XENONnT/straxen#342]
We are missing the acquisition monitor in the documentation.

**Comment by jorana** [comment]
Do you the plugins:
- https://straxen.readthedocs.io/en/latest/reference/datastructure.html#veto-intervals
- https://straxen.readthedocs.io/en/latest/reference/datastructure.html#aqmon-hits
- https://straxen.readthedocs.io/en/latest/reference/datastructure.html#online-monitor

**Comment by WenzDaniel** [comment]
Ah yes, I have not seen them. There may be a bit hidden in the TPC data structure since there are not directly visible in the dependency graph.

**Comment by jorana** [comment]
Similarly the online monitor is not shown top level, I have an idea to solve this let me see if it makes sense:
- https://straxen.readthedocs.io/en/latest/reference/datastructure.html#event-info

**Comment by jorana** [comment]
@WenzDaniel , this was what I thought about. Not sure if it makes things much better... 
![afbeelding](https://user-images.githubusercontent.com/22295914/105627969-4c879480-5e3a-11eb-8a48-8c4f01227485.png)

**Comment by jorana** [comment]
Closing this issue. If we want to revisit this, please reopen the issue.

Meanwhile, the documentation idea is saved here:
https://github.com/jorana/straxen/tree/structure_idea
