### ISSUE TITLE
Define peak regions in waveform viewer

### ISSUE THREAD

**Issue by jpienaar13** [XENONnT/straxen#346]
It would be beneficial if we can add grey (or some other colour?) shaded bands in the time series plot, around the location of the MS1/AS1/MS2/AS2. This will help identify where the split occurs when the peaks follow directly one one another.

**Comment by jpienaar13** [comment]
Also, we should plot the baseline in the S1/S2 windows to check for any baselining issues.

**Comment by WenzDaniel** [comment]
You mean some average baseline over all channels? Not sure if we can add 500 baseline in way such that things stay clear.

**Comment by jpienaar13** [comment]
Yeah definitely the average baseline and not 500 baselines.

**Comment by jorana** [comment]
@jpienaar13 is this still open or can we close it?

**Comment by JoranAngevaare** [comment]
Since this is stale, I'm closing it
