### ISSUE TITLE
Dropping datafields in numba from dtype to dtype

### ISSUE THREAD

**Issue by jorana** [XENONnT/straxen#353]
We have a few instances in strax/straxen where we basically hardcode copy a given datatype to another (e.g. [this one](https://github.com/XENONnT/straxen/blob/master/straxen/plugins/veto_hitlets.py#L140)). We might want to use a more dynamic function like this one from the [PyHEP Numba tutorial on February 3, 2021](https://nbviewer.jupyter.org/github/jpivarski-talks/2021-02-03-pyhep-numba-tutorial/blob/main/tutorial.ipynb) from Jim Pivarski. Might be much easier to maintain than having to make a new patch every time a dtype name changes:

```python
args = [
    np.random.normal(0, 1, 1000000),
    np.random.normal(0, 1, 1000000),
    np.random.normal(0, 1, 1000000),
    np.random.normal(0, 1, 1000000),
#     np.random.normal(0, 1, 1000000),
]

code = f"""
@nb.vectorize
def sum_in_quadrature({", ".join("p%d" % i for i in range(len(args)))}):
    # compiled for exactly {len(args)} arguments
    return np.sqrt({" + ".join("p%d**2" % i for i in range(len(args)))})
"""

print(code)
exec(code)
sum_in_quadrature(*args)
```

**Comment by WenzDaniel** [comment]
Sorry, by accident...
