### ISSUE TITLE
Wrong color representation in straxen.plot_pmts()

### ISSUE THREAD

**Issue by GiovanniVolta** [XENONnT/straxen#356]
straxen.plot_pmts(...) doesn't  attribute the right colour. The colorbar is valid only for the bottom PMT array.
I noticed plotting the results of PMT calibration. Here some example:

-  Top array between [1,2] and bottom array between [0,1]. The colour suggests that both the array are between [1,2]
``
fix = np.random.uniform(low=1, high=2, size=494)
fix[:253] = np.random.uniform(low=0, high=1, size=253)
straxen.plot_pmts(fix)
``
[top01_bot_12.pdf](https://github.com/XENONnT/straxen/files/5924821/top01_bot_12.pdf)

-  Top array between [0,1] and bottom array between [1,2]. As before, the colour suggest that both the array are between [0,1]
``
fix = np.random.uniform(low=1, high=2, size=494)
fix[:253] = np.random.uniform(low=0, high=1, size=253)
straxen.plot_pmts(fix)
``
[top12_bot_01.pdf](https://github.com/XENONnT/straxen/files/5924823/top12_bot_01.pdf)

Then, the colour representation is given always from the bottom array. Am I wrong? 

I will try to look into the function. For the moment let me open this issue. You might know already where is the problem.

**Comment by jorana** [comment]
@GiovanniVolta , thanks for spotting it, should be fixed in #357
