### ISSUE TITLE
Alternative s2 positions in event_posrec_many

### ISSUE THREAD

**Issue by jingqiangye** [XENONnT/straxen#371]
@DonNabla reported that the alt_s2 positions for all algorithms in `event_posrec_many` are all 0. After checking, we think is due to a bug in [L263](https://github.com/XENONnT/straxen/blob/master/straxen/plugins/event_processing.py#L263), which probably should be `posrec_result[f'alt_s{s_i}_{name}'] = secondary_s[s_i][name]`?

**Comment by jorana** [comment]
Many thanks for reporting this #372 should fix it.
