### ISSUE TITLE
Add rise time in event data kind

### ISSUE THREAD

**Issue by jingqiangye** [XENONnT/straxen#381]
Hey, I just found that we don't have rise time information for S1/S2 at event level. I think it will be useful to add them, especially for S1. Is there a reason not to add them, or I overlooked something?

**Comment by jorana** [comment]
You can always do something:
```python
st.get_array(run_id, "peak_basics", time_range=[event_i["s1_time"], event_i["s1_endtime"]])['rise_time']
```

My guess is that we'd want to not end up with the pax situation where event basics is an array with >200 fields. Technically it's trivial to add this info, so if there is a need, it's not hard to add. Perhaps you or an AC may comment if we want this.

**Comment by jingqiangye** [comment]
Thanks Joran for the suggestion. I tried the following code but seems the speed is ~300 ms/peak.. did I do smth wrong? But even if it's 35 ms/peak, it still took a while to load. 

```
risetime = []

for idx in tqdm(range(1, len(df1))):
    _rt = st.get_array(run_id, "peak_basics", time_range=[df1.loc[idx, "s1_time"], df1.loc[idx, "s1_endtime"]], 
                       progress_bar=False)['rise_time']
    risetime.append(_rt)
```

@skazama proposed the idea of adding an extended plugin for event data kind, similar to the [Extended minitree in hax](https://github.com/XENON1T/hax/blob/master/hax/treemakers/common.py#L26-L199). In this way, ppl can avoid 200ish columns if they don't need the extra info, but can still access that information quickly when necessary. Do you think it makes sense? @jorana

**Comment by jorana** [comment]
Hi Jingqiang, sure we could definitely do that, I'm also fine with adding it to event basics for the record, just stating some considerations above. If you guys want it, we can make it so, it's just that it's always easier to add and add things rather than removing some variables.

The rest of my reply below is not at all really addressing the issue, just wrote it out because it might help you. Funny that your run is so slow. I just ran yours and it also made 33 it/s. Must be something that is different on how the run is stored.

Nevertheless if you want to do this a bit faster it's of course better to not make a big for loop. You can e.g. do
````python
%%time
events = st.get_array('012486', "event_basics")
peaks = st.get_array(run_id, "peak_basics")

#CPU times: user 133 ms, sys: 17.1 ms, total: 150 ms
#Wall time: 477 ms

%%timeit
# only look at events with an S1
event_mask = events['s1_time']>0
selected_events = events[event_mask]

# Create some time containers based on the S1s
containers = np.zeros(len(selected_events), dtype=strax.time_fields)
containers['time'] = selected_events['s1_time']-1
containers['endtime'] = selected_events['s1_endtime']+1

# Do smart for loop using numba
idxs = strax.fully_contained_in(peaks, containers)
mask = idxs >=0

# We get our much desired rise time from the peaks
s1_rise_time = peaks[mask]['rise_time']
assert len(s1_rise_time) ==  len(selected_events)
# 3.45 ms ± 56.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

**Comment by jingqiangye** [comment]
Thanks @jorana  this method is much faster! Regarding the extended plugin, probably we can discuss more when Shingo is up. Personally I like that idea :)

**Comment by skazama** [comment]
Concerning the extended plugin, I think we will definitely need it for high level analysis. We don't need to add all variables used in the [extended plugin](https://github.com/XENON1T/hax/blob/master/hax/treemakers/common.py#L26-L199) for 1T (too much, I guess). In addition to rise_time, we will probably need following variables:

- s1(s2)_rise_time: for removing single-e reconstructed as S1s 
- s1(s2)_range_90p_area: for S1width and  SingleElectronS2s cuts
- s1(s2)_largest_hit_area: to reject peaks with noisy PMTs (MaxPMT cut)
- s1(s2)_largest_hit_channel: to reject peaks with noisy(suspicious) PMTs
- pattern_fit for s1(top and bottom separately), s2 and largest_other_s2: for removing gamma/neutron + X (double-scatter) events
- area_before_main_s2: to reject events with lots of peak_area before main S2 (PreS2Junk)
- s2_over_tdiff: for removing suspicious events after very large S2s (S2TailCut)

Maybe @jingqiangye @ershockley or @michellegalloway can comment about cuts needed for the lowER search

**Comment by jingqiangye** [comment]
Just add another variable:

* `s1_area_fraction_top_probability`: p-values for S1 AFT given its reconstructed interaction position for S1 AFT cut

**Comment by jingqiangye** [comment]
Just link the [google spreadsheet](https://docs.google.com/spreadsheets/d/1I-0gr4Mwmbo46gKTHm6O_XAO1qTGgRZs9PK4Z427LVY/edit#gid=0) here for documentaiton.

**Comment by jorana** [comment]
With #420 merged, I think we can safely close this PR. Thanks all!
