### ISSUE TITLE
Idea: straxen.clear_all_pycache

### ISSUE THREAD

**Issue by jorana** [XENONnT/straxen#39]
Maybe it would be a nice feature to add a function `clear_all_pycache` or the like to delete all `__pycache__` folders. Sometimes (especially after doing a git pull) Numba throws some errors that can simply be solved by removing everything stored in several __pycache___ folders.

On the other hand I’m not sure if this is a feature that strax/straxen should have. Even better of course would be if numba wouldn’t be failing (than this monkey-patch would be obsolete).

If others see merrit in this too I'll come up with a simple function to add to straxen.

**Comment by JelleAalbers** [comment]
Yes, the issue https://github.com/AxFoundation/strax/issues/180 is irritating, I'm hitting it many times myself too. Since it always seems to be the same one that gives problems, I am going to try to disable numba's caching for this function in the next strax release. Maybe that will already help.

**Comment by jorana** [comment]
Thanks Jelle, I'll close this issue for now. It doesn't make sense to have duplicate issues.
