### ISSUE TITLE
optimize nT event finding parameters

### ISSUE THREAD

**Issue by JoranAngevaare** [XENONnT/straxen#454]
Some detailed studies on the best parameters would improve our event reconstruction. A couple of parameters remain un-optimized:
- [ ] trigger_min_area
- [ ] trigger_max_competing
- [x] left_event_extension & right_event_extension (partially optimized but may require further tweaking)

**Comment by jorana** [comment]
Perhaps an idea worth considering is making the left (/ right) extension dependent on the drift velocity:
https://github.com/XENONnT/straxen/blob/f1e1c2138d6d79f7db83a12961435c4a8c397289/straxen/plugins/event_processing.py#L303

As in, redefine the the left extension to be added to one drift length of the TPC. That way, we could have a variable event duration based on the drift time from CMT.

**Comment by jorana** [comment]
left and right extensions are optimized

**Comment by JoranAngevaare** [comment]
this is done higher level
