### ISSUE TITLE
MergedS2s fails for empty sets of peaklets

### ISSUE THREAD

**Issue by jorana** [XENONnT/straxen#49]
MergedS2s is causing problems when processing an empty set of peaklets. It doesn't seem to get to the compute part https://github.com/XENONnT/straxen/blob/master/straxen/plugins/peaklet_processing.py#L170, hence it also does not get to the ```if``` statement at the end of compute (https://github.com/XENONnT/straxen/blob/master/straxen/plugins/peaklet_processing.py#L219).

**Comment by JelleAalbers** [comment]
This will be a tough one to solve. The fundamental issue is that chunks are not passed along with metadata indicating which time they correspond to, which makes empty chunk handling a pain.

**Comment by JelleAalbers** [comment]
The improved empty chunk handling in the new strax version should solve this. The offending code in straxen's MergedS2s is now gone. Let me know if you see this again -- then it will almost certainly be a completely different underlying issue.

**Comment by jorana** [comment]
Thanks Jelle!
