### ISSUE TITLE
Scada calls fail if float times are used due to using len(str(start)) to do log10(start)

### ISSUE THREAD

**Issue by kdund** [XENONnT/straxen#491]
The line here: 
https://github.com/XENONnT/straxen/blob/42d3f3839e0f771393c6dbbc61d8380320d87d71/straxen/scada.py#L233
uses the length of the string representation of the number to do log10
that works for ints, not for floats. 
If only ints are to be used, I think a separate test should be done for this.

**Comment by jorana** [comment]
Should be fixed in #560
