### ISSUE TITLE
ZeroDivisionError in holoviews display

### ISSUE THREAD

**Issue by JelleAalbers** [XENONnT/straxen#52]
As mentioned in https://github.com/XENONnT/straxen/issues/48#issuecomment-580681218, you currently get a ZeroDivisionError when trying to use the holoviews display. We should post the full error trace here and then try to figure out what (upstream?) change caused this to appear.

**Comment by philippjfr** [comment]
Let us know what we (HoloViz developers) can do to help debug this.

**Comment by JelleAalbers** [comment]
@philippjfr Thank you! It appears that this problem has resolved itself: after some updates in our environment we do not see this anymore and our holoviews display works again. Perhaps it was a particular combination of versions that caused this; if we see it again, we'll reopen and try to track it down.
