### ISSUE TITLE
hitlet-processing is bugged (or flaky)

### ISSUE THREAD

**Issue by JoranAngevaare** [XENONnT/straxen#596]
**Describe the bug**
Processing on the event-builder fails due to hitlet-processing. It remains unclear where this bug is (either MV or NV processing)

**To Reproduce**
Process 25576 

**Expected behavior**
Don't fail

**Versions**
Please add the output of:
```
(py38) xedaq@eb4:~$ python -c "import straxen ; straxen.print_versions()"
Working on eb4.xenon.local with the following versions and installation paths:
python  v3.8.5  (default, Sep  4 2020, 07:30:14) [GCC 7.3.0]
strax   v0.16.1 /home/xedaq/software/strax/strax
straxen v0.19.3 /home/xedaq/software/straxen/straxen
```

**Traceback**
```
Exception info: concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/xedaq/miniconda/envs/py38/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/xedaq/software/npshmex/npshmex.py", line 193, in shm_wrap_f
    result = f(*args, **kwargs)
  File "/home/xedaq/software/strax/strax/plugin.py", line 1032, in do_compute
    r = p.do_compute(**compute_kwargs)
  File "/home/xedaq/software/strax/strax/plugin.py", line 525, in do_compute
    result = self.compute(**kwargs)
  File "/home/xedaq/software/straxen/straxen/plugins/veto_hitlets.py", line 134, in compute
    strax.hitlet_properties(temp_hitlets)
ZeroDivisionError: division by zero
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xedaq/software/straxen/bin/bootstrax", line 1293, in run_strax
    st_make()
  File "/home/xedaq/software/straxen/bin/bootstrax", line 1271, in st_make
    st.make(run_id, targets,
  File "/home/xedaq/software/strax/strax/context.py", line 1215, in make
    for _ in self.get_iter(run_ids[0], targets,
  File "/home/xedaq/software/strax/strax/context.py", line 1099, in get_iter
    generator.throw(e)
  File "/home/xedaq/software/strax/strax/context.py", line 1072, in get_iter
    for n_chunks, result in enumerate(strax.continuity_check(generator), 1):
  File "/home/xedaq/software/strax/strax/chunk.py", line 303, in continuity_check
    for chunk in chunk_iter:
  File "/home/xedaq/software/strax/strax/processor.py", line 286, in iter
    raise exc.with_traceback(traceback)
  File "/home/xedaq/software/strax/strax/mailbox.py", line 491, in divide_outputs
    result = next(source)
  File "/home/xedaq/software/strax/strax/mailbox.py", line 412, in _read
    res = msg.result()
  File "/home/xedaq/miniconda/envs/py38/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/home/xedaq/miniconda/envs/py38/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
ZeroDivisionError: division by zero
```

**Comment by WenzDaniel** [comment]
I think it must be either something with the ebs or some kind of race condition I do not know. But I cannot reproduce on dali neither for nveto nor mveto. I checked both with run 025465.

Can we try to set https://github.com/AxFoundation/strax/blob/ee04635d125431b798170cc5f5c4ceb72bd4e42d/strax/processing/hitlets.py#L259-L260 cache to False and see if the error persists? Which numba and numpy version are we using on the ebs? I tested with:

- numba: '0.52.0'
- numpy: '1.20.0'

**Comment by WenzDaniel** [comment]
I checked some more log files and for `025577` hitlets were produced successfully for both detectors in the end. Although we hit the same div by zero error during one of the tries. Hence I think it sounds even more like some race condition with numba cached functions.

**Comment by jorana** [comment]
@WenzDaniel , I can now also not reproduce, which makes it all the more frustrating. What kind of race-conditions would you have in mind?

On the DAQ we are running with:
```
(py38) xedaq@eb0:~/joran/strax_data$ python -c "import straxen ; straxen.print_versions(['numba', 'numpy'])"
python  v3.8.5  (default, Sep  4 2020, 07:30:14) [GCC 7.3.0]
numba   v0.53.1 /home/xedaq/miniconda/envs/py38/lib/python3.8/site-packages/numba
numpy   v1.19.4 /home/xedaq/miniconda/envs/py38/lib/python3.8/site-packages/numpy
```

Numpy 1.20 is not compatible with tensorflow, unless you are on some pre-release?

**Comment by jorana** [comment]
Just to be sure, I also updated the software to:
```
install numpy==1.19.5 
tensorflow~=2.4 
utilix==0.6.0 
numba==0.53.1 
npshmex==0.2.1 
blosc==1.10.4 
pandas==1.2.5 
psutil==5.8.0 
scikit-learn==0.24.2 
scipy==1.7.0 
zstd==1.5.0.2
```

**Comment by WenzDaniel** [comment]
> What kind of race-conditions would you have in mind? 

Something similar like we encountered before that some numba chached function is called in one thread while another thread is overwritting the current cache index. I do not know. Hence, my suggestion to turn off the caching and see if the problem vanishes. 

> Numpy 1.20 is not compatible with tensorflow, unless you are on some pre-release?

To be honest I do not know. I never worked much with tensorflow. I only installed it to process our peak data:
```
tensorboard               2.4.1              pyhd8ed1ab_0    conda-forge
tensorboard-plugin-wit    1.8.0              pyh44b312d_0    conda-forge
tensorflow                2.3.0           eigen_py38h71ff20e_0
tensorflow-base           2.3.0           eigen_py38hb57a387_0
tensorflow-estimator      2.4.0              pyh9656e83_0    conda-forge
```
I also made a small fix in https://github.com/AxFoundation/strax/pull/491 although I doubt that it is related.

**Comment by WenzDaniel** [comment]
Just for the record. We changed the order in which we process our data and processing nveto and mveto data with some time in between works for the moment. However, so far I do not have any idea how this issue can be fixed more fundamentally.

**Comment by jorana** [comment]
@WenzDaniel , since we changed this behavior (first fully process the NV chain, then the MV chain) the error hasn't occurred anymore.

Could it be that some of the data-formats is different in a way that it causes inconsistencies when re-using the cached numba function?

**Comment by jorana** [comment]
🤔 , the stink builds, also when doing systems separately (e.g. run 26131), we run into this issue

**Comment by JoranAngevaare** [comment]
Seems solved or at least not found anymore
