### ISSUE TITLE
Stop making `events` datatype

### ISSUE THREAD

**Issue by jorana** [XENONnT/straxen#619]
## Proposal

- Stop saving the `events` datatype 
- include the `event_number` field in `event_basics`.
- Don't include `events` in `event_info`

![afbeelding](https://user-images.githubusercontent.com/22295914/127978991-400b4a3c-ee64-444f-9c3c-bda3cd6e9b29.png)

## Why
`events` is currently almost an empty datatype (`time`, `endtime`, `event_number`). For this one extra field, we might as well add it to the `event_basics`. An additional advantage would be that we could build `event_info` from `event_basics` only. It would require less files/dependencies to build `event_info` so that would also be slightly quicker.

**Comment by WenzDaniel** [comment]
Sounds good. I cannot spot any possible show stoppers.
