### ISSUE TITLE
Wrong Binomial test for low PE events with S1 AFT = 0

### ISSUE THREAD

**Issue by GiovanniVolta** [XENONnT/straxen#629]
**Describe the bug**
I believed the current binomial test for low PE events with S1 AFT small, or even equal to 0, is wrong. The algorithm computes the two-side test whether we are able to find j, on the other side of the binomial distribution, such that Binom(j; n,p)=Binom(k;n,p) where k is S1 in the top array, n is the S1 and p is the S1 AFT prob. Otherwise, we compute the one side test. See [here](https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:giovo:preliminary_s1aft_cut#introduction) for more details.

In the current implementation, the low PE events at the bottom of the TPC are wrongly treated. We basically don't account for the fact that the Binomial distribution, for low S1 and low S1 aft prob, can decrease monotonically.

- Three example:
![S1AFT_issue_1](https://user-images.githubusercontent.com/38431109/128721999-db489624-2160-4afd-8553-c8a96c263020.png)
![S1AFT_issue_3](https://user-images.githubusercontent.com/38431109/128722004-1a15eb16-39f7-4674-85c0-1fd8fc4d04e0.png)
![S1AFT_issue_2](https://user-images.githubusercontent.com/38431109/128722007-00943954-5d26-4a52-a0e2-4142b530ba06.png)

**To Reproduce**
For reproducing the error, you have just to use the current algorithm in the [event_pattern_fit plugin](https://github.com/XENONnT/straxen/blob/7fe998d21180a89b92d2cbaed4f59f92d17ffff5/straxen/plugins/event_patternfit.py#L367). Nevertheless, [here](https://gist.github.com/GiovanniVolta/ce6d937a212e5b5da12b805a9a6eff44) the gist with which  you can get the 3 plots above.

**Expected behavior**
If Binom(0;n,p) is the maximum, the binomial test should be always a one side test. The expected behaviour is shown in the following plots. The _binom_test_ can be updated according to this [gist](https://gist.github.com/GiovanniVolta/f546fc997ccfb03c05dac9d9453ee956)

![S1AFT_solved_2](https://user-images.githubusercontent.com/38431109/128725003-62d6860f-1dd4-440e-9237-0ebc6b61f84f.png)
![S1AFT_solved_3](https://user-images.githubusercontent.com/38431109/128725005-d6a73af9-53a0-4a7f-97cd-026d077815c8.png)
 
![S1AFT_solved_1](https://user-images.githubusercontent.com/38431109/128724993-53031975-ce40-4ec3-83ea-f69c6a91806c.png)

**Versions**
Please add the output of:
```
Working on midway2-0416.rcc.local with the following versions and installation paths:
python	v3.8.11	(default, Aug  3 2021, 15:09:35) [GCC 7.5.0]
strax	v0.16.1	/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.8/site-packages/strax
straxen	v0.19.3	/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.8/site-packages/straxen
```

**Comment by kdund** [comment]
Well spotted, moving to 2nd version makes sense

**Comment by WenzDaniel** [comment]
Hi Giovanni, good catch. Based on your gist the changes are hard to see. Do you think it can be implemented in https://github.com/XENONnT/straxen/pull/625? Or do you need some additional special functions from scipy except the once for which I added a numba representative?

**Comment by GiovanniVolta** [comment]
Hi @WenzDaniel, yes it can be implemented. I already did it and tested it. Let me push the updates to the branch

**Comment by GiovanniVolta** [comment]
[Here](https://github.com/XENONnT/straxen/blob/aefd7241bba9fbdda486b95418f74e2f7959a55a/straxen/plugins/event_patternfit.py#L370) the binomial test update.

I have one more cases for which I am not sure if we are doing the right thing. It is the case when the binomial distribution is not symmetric, the skewness is negative, and Binom(0, n, p) is different from 0. Currently, the p-value for all the events with Binom(j; n, p) < Binom(n; n, p) is defined by one-side integral. See few plots which illustrate the cases:

![S1AFT_10](https://user-images.githubusercontent.com/38431109/128898344-a0610803-3d8a-4b29-b071-1447daf1e6ad.png)
![S1AFT_0](https://user-images.githubusercontent.com/38431109/128898345-9c04bd6a-a746-442f-a425-bc5a07c3875b.png)
![S1AFT_24](https://user-images.githubusercontent.com/38431109/128898349-4ef817aa-5e9d-4015-af2b-dbcbeaaa88d7.png)

I think it is fine, but I would like your opinion.

**Comment by GiovanniVolta** [comment]
After a discussion with @kdund, [I have changed again](https://github.com/XENONnT/straxen/blob/d5567b488f2f8be8969b159df8bc7d59341d7f4f/straxen/plugins/event_patternfit.py#L433) the p-value calculation such that the sensible direction of more extreme is where S1s has equally small or smaller PDFs. Here below an example:
![sa_aft_fix_bug](https://user-images.githubusercontent.com/38431109/129003883-3a8ad83d-b704-41ff-9e2a-26f6955cb7d3.png)

**Comment by GiovanniVolta** [comment]
Yes, I will. I am processing ~50ish Radon and AmBe runs. As soon as they are ready, I will produce the plots you asked me
