### ISSUE TITLE
Rucio Front-end does not support/ignore superruns. 

### ISSUE THREAD

**Issue by WenzDaniel** [XENONnT/straxen#668]
**Describe the bug**
Issue reported by @jjakob03 . It is the same as for our [rundb-frontend](https://github.com/XENONnT/straxen/pull/627). The rucio-frontend will raise an error if the user wants to load a sueprrun. 

**To Reproduce**
Insert the MWE of how to reproduce the error
```python
st = straxen.contexts.xenonnt_online()
st.define_run('_test', ('025472', '025473'))
st.set_context_config({'write_superruns': True})
st.make('_test', 'event_info')
st.select_runs(available=('event_info',))
```

**Expected behavior**
The rucio front-end should ignore corresponding runs when searching for data.

**Comment by ershockley** [comment]
@WenzDaniel and @jjakob03  thanks for raising. I'm just wondering though -- unless we want to store superruns in rucio (I'm almost sure we do not) I do not think it makes sense for the rucio front end to support it. What do you think?

**Comment by WenzDaniel** [comment]
> I'm just wondering though -- unless we want to store superruns in rucio (I'm almost sure we do not) I do not think it makes sense for the rucio front end to support it. What do you think?

Yes, I fully agree. We just need a "if run_id.starts_with('_') .... ignore". And a test which checks all front-ends since this pops up now the second time already. I can do it at some point this week.

**Comment by JoranAngevaare** [comment]
> checks all front-ends since this pops up now the second time already

Or you could disable multirun support for frontends by default (i.e. add this one line you mention in strax, not straxen) because multiruns only really work for the DataDirectoey frontend. I'm going to guess that it also does not work for the online monitor- or zipfile- frontends in strax.

**Comment by WenzDaniel** [comment]
Okay I did the required changes in strax https://github.com/AxFoundation/strax/pull/532, but the issue is that our rucio-frontend is not following the same logic as our other frontends. E.g. it overwrites the default find_several method without using the find-method.

**Comment by JoranAngevaare** [comment]
> Is it possible to change this? Otherwise I would have to add an additional workaround in straxen.

This is the whole point of the rucio/rundb frontend since it's much more effective to use a single query rather than many so I would not change that. I'll look into it later this week if I see an easy solution.

**Comment by WenzDaniel** [comment]
Okay sorry in this case I am not sure what you meant with 

> Or you could disable multirun support for frontends by default (i.e. add this one line you mention in strax, not straxen) because multiruns only really work for the DataDirectoey frontend. 

At which place do you had in mind to add this line. If the rucio front-end is not inheriting the same methods I do not see how I would implement it. At least the way I had in mind apparently does not work.
