### ISSUE TITLE
Rucio front end looks for local files if one with the same name exists.

### ISSUE THREAD

**Issue by michaweiss89** [XENONnT/straxen#670]
**Describe the bug**

**To Reproduce**
Insert the MWE of how to reproduce the error
```python
YOUR CODE GOES HERE
```

**Expected behavior**

**Screenshots**

**Versions**
Please add the output of:
```
straxen.print_versions()
```

**Comment by michaweiss89** [comment]
I tried to download a certain chunk with rucio front end but it was looking at local files and did not find it. 
There was an incomplete raw record file of the same run and only after deleting it did rucio downloaded the chunk.

run_id, target = '020315', 'raw_records'
s2_time = 1621897731731375152
st = straxen.contexts.xenonnt(
    use_rucio=True,
    use_rucio_remote=True,
   # output_folder = os.path.join(os.environ['SCRATCH'], './rucio_staging_dir'),
)
st.storage[-1].backends[-1].download_heavy = True
for chunk in st.get_iter(run_id, target, # or touching
             time_range=(
                  # get the s1 from this event
                 int(s2_time-4*30000),
                 int(s2_time+4*60000),
            )):
    print(chunk)

output:

FileNotFoundError: [Errno 2] No such file or directory: './strax_data/020315-raw_records-rfzvpzj4mf/raw_records-rfzvpzj4mf-000019'

Expected behavior:
If there is a raw record file with the same name if it does not find the chunk it should download the missing chunk with rucio.

Working on midway2-0424.rcc.local with the following versions and installation paths:
python	v3.8.11	(default, Aug  3 2021, 15:09:35) [GCC 7.5.0]
strax	v1.0.0	/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.8/site-packages/strax
straxen	v1.0.0	/opt/XENONnT/anaconda/envs/XENONnT_development/lib/python3.8/site-packages/straxen
cutax	v0.2.0	/home/weiss89/.local/lib/python3.8/site-packages/cutax

**Comment by JoranAngevaare** [comment]
Same issue as https://github.com/XENONnT/straxen/issues/586

**Comment by JoranAngevaare** [comment]
Should be fixed in #688, #694, please reopen if persistent
