### ISSUE TITLE
PyMongo 4.0 includes breaking changes

### ISSUE THREAD

**Issue by jmosbacher** [XENONnT/straxen#782]
pymongo 4.0 was released with some breaking [changes](https://pymongo.readthedocs.io/en/stable/changelog.html) and since our requirement for this package is not pinned (comes from strax) this is causing tests to fail.

So far I found two issues that need fixing to adapt to the new version:

1. Cursor no longer has the .count() method, needs to be replaced with collection.count_documents(query)
2. GridFS no longer computes the md5 hash for you. We need to add this ourselves.
3. Looks like default readPreference is now Primary, since our primary is not accessible from everywhere this causes server selection timeout in tests. When using utilix to get the client this is not an issue since utilix sets the readPreference explicitly (thanks to @ershockley s superior attention to details)

There may be others. will add them here as I find them.

**Comment by JoranAngevaare** [comment]
One other thing that is that `tz_aware` is now set to default to `False`, I'm quite sure that will induce a lot of issues in e.g. bootstrax

**Comment by JoranAngevaare** [comment]
Thanks for the issue, it's now in the requirements file so I'll close the issue for now

**Comment by jmosbacher** [comment]
Should we open an issue in strax for each of the known issues that need to be solved before we move to pymongo 4.0?
