### ISSUE TITLE
Make enum for classification types

### ISSUE THREAD

**Issue by JelleAalbers** [XENONnT/straxen#8]
Observation from @jpienaar13: it would be useful if straxen had an enum (see https://docs.python.org/3/library/enum.html#intenum) that encodes that 1 corresponds to S1, 2 to S2, and higher numbers to potential future peak types we might want to add.

**Comment by jorana** [comment]
I tried this, but it did not like working together with numba which is quite essential.

**Comment by jorana** [comment]
See my comment above
