### ISSUE TITLE
Tensorflow attributes are non-pickable (bad for profiling and mutliprocessing)

### ISSUE THREAD

**Issue by JoranAngevaare** [XENONnT/straxen#811]
Maybe, like https://github.com/AxFoundation/strax/pull/588, we should avoid setting [TF models as class ](https://github.com/XENONnT/straxen/blob/5c9a33467f362dabdffc75a1164a0bf312d92708/straxen/plugins/position_reconstruction.py) attributes.

I'm not sure how large the networks are and if we would need to clean them up after the plugin finished to avoid memory leaks.

**Comment by jmosbacher** [comment]
Of course I would advocate for getting rid of the `setup()` code and just use a URLConfig with caching like the example I give in #758.
But then again, I am very biased ;)

**Comment by JoranAngevaare** [comment]
Yeah I fully agree it would be nice to start using the `URLConfig`.

The only issue with these neural nets is that you need to [unpack them](https://github.com/XENONnT/straxen/blob/5c9a33467f362dabdffc75a1164a0bf312d92708/straxen/plugins/position_reconstruction.py#L72-L74). So if you just do the naive thing, you end up un-tarring the network for each chunk.

**Comment by jmosbacher** [comment]
Thats exactly what the `URLConfig(cache=True)` is for, it should only be loaded once for each python process.
