### ISSUE TITLE
Normalize line endings

### ISSUE THREAD

**Issue by jmosbacher** [XENONnT/straxen#833]
Looks like we have a mixture of LF and CRLF line endings.
Maybe we should implement one of [these](https://www.aleksandrhovhannisyan.com/blog/crlf-vs-lf-normalizing-line-endings-in-git/) solutions so we dont waste hours trying to figure out why git diff shows the entire file as changing when we just edited one line...

**Comment by WenzDaniel** [comment]
Yes, it is a bit annoying. I usually set it for each repository manually, but I like this `.gitattribute` file. For me it is fine to add.
