### ISSUE TITLE
`correction_options`  doesn't work for `URLConfigs`

### ISSUE THREAD

**Issue by JoranAngevaare** [XENONnT/straxen#864]
`correction_options` is not working for `URLConfigs` because it assumes the tuple config type and otherwise doesn't really understand it's a CMT option

As there are no adequate tests for it, these kind of bugs aren't solved before releases

**Comment by jmosbacher** [comment]
hmm, i thought Evans PR was supposed to fix this? Ok, in any case a more long term solution is already prepared in PR #827. I just need to add some more testing and it will be ready for review.

**Comment by JoranAngevaare** [comment]
See #865
