### ISSUE TITLE
Event level S1 threshold must be reflected in triggering peaks

### ISSUE THREAD

**Issue by WenzDaniel** [XENONnT/straxen#881]
Currently, we only set the [S1 PMT threshold](https://github.com/XENONnT/straxen/blob/4e288fd1283f99564b990c687d982cb8c9162cbc/straxen/plugins/event_processing.py#L132) during the event-building step but not during the search for triggering peaks. If we allow S1 as triggering peaks and increase the threshold to be larger than the peak-level threshold this will lead to ambiguous events.

**Comment by JoranAngevaare** [comment]
Though not technically incorrect, it's extremely unlikely to see a 100 PE S1 with a tight coincidence of just 2
