### ISSUE TITLE
Add warning when xenonnt context is called from outside of cutax

### ISSUE THREAD

**Issue by jmosbacher** [XENONnT/straxen#959]
@ershockley pointed out that using a context directly from straxen (bypassing cutax) is not the proper way of starting an analysis.  We should have some warning indicating this so analysts dont e.g. run an old notebook that creates a context directly from straxen and not understand why they get weird results.

The simplest implementation would be to add a flag to `contexts.xenonnt` which cutax would set so as to inhibit the warning.
e.g.
```python
def xenonnt(cmt_version='global_ONLINE', _from_cutax=False,  **kwargs):
    """XENONnT context"""
    if not _from_cutax:
        warn(...)
...
```

This would not break existing code but would at least warn people running analyses the wrong way.

**Comment by JoranAngevaare** [comment]
added in #1020 and https://github.com/XENONnT/cutax/pull/165
