### ISSUE TITLE
Don't allow `bootstrax --production` for finished runs

### ISSUE THREAD

**Issue by JoranAngevaare** [XENONnT/straxen#965]
If we have already finished a run, we shouldn't be allowed to say `bootstrax --production --process <finished_run>` since it results in a "failure" since there is no live data anymore etc etc.

**Comment by JoranAngevaare** [comment]
@mflierm , would you want to add a check that fails when `bootstrax --production --process <finished_run> ` is specified? I think it's important we add this

**Comment by mflierm** [comment]
Just tried something here, let me know what you think! :)

https://github.com/XENONnT/straxen/commit/b3e1d91d43caa41a64cfa4fc2bb20687fd89455e#commitcomment-71713357

**Comment by JoranAngevaare** [comment]
fixed in https://github.com/XENONnT/straxen/pull/1024 by @mflierm
