### ISSUE TITLE
Better rundb registration

### ISSUE THREAD

**Issue by JelleAalbers** [XENONnT/straxen#98]
When strax registers new rundb entries, the host field https://github.com/XENONnT/straxen/blob/4c59975e39fb44bd70a426e949c061511ba54eef/straxen/rundb.py#L158 should probably refer to the hostname alias ('dali') rather than the full hostname ('dali-login1.etc.etc').

We should also include the lineage hash of the data (e.g. in the meta field under lineage_hash) rather than just the lineage. This will make searching a lot easier.

**Comment by JoranAngevaare** [comment]
Since this is now handled mostly by rucio I'm closing this issue
